//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertySystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class w_admin
    {
        public int id { get; set; }
        [DisplayName("登录账号")]
        public string username { get; set; }
        [DisplayName("登录密码")]
        public string pass { get; set; }
        [DisplayName("管理员名称")]
        public string nickname { get; set; }
        [DisplayName("管理员权限")]
        public Nullable<int> power { get; set; }
        [DisplayName("创建时间")]
        public Nullable<System.DateTime> createtime { get; set; }
    }
}
