//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertySystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class w_system_params
    {
        [DisplayName("系统参数id")]
        public int id { get; set; }
        [DisplayName("代码")]
        public string code { get; set; }
        [DisplayName("名称")]
        public string name { get; set; }
        [DisplayName("装修标准")]
        public string type { get; set; }
    }
}
